### ISSUE TITLE
What is the need of this lib

### ISSUE THREAD

**Issue by ammaratef45** [okkez/coveralls-lcov#14]
I found people using this for travis but didn't know why and didn't understand the output lcov.info file.
The readme didn't help too much for this too

**Comment by okkez** [comment]
You need learning about lcov before using this tool.

* http://ltp.sourceforge.net/coverage/lcov.php
* https://github.com/linux-test-project/lcov
* lcov(1)

**Comment by ammaratef45** [comment]
@okkez Great help, thanks
