### ISSUE TITLE
[question/feature request] Uploading of content of generated files

### ISSUE THREAD

**Issue by Nic30** [okkez/coveralls-lcov#15]
Hello,

is it possible include content of generated files to a report?

I do have some some generated files in my project https://coveralls.io/builds/25742378/source?filename=src/verilogPreproc/verilogPreprocParser/verilogPreprocLexer.cpp

I do not know how to add them to https://docs.coveralls.io/api-reference /  SOURCE FILE / source in report so coveralls can visualize it.

Thanks

**Comment by okkez** [comment]
AFAIK, coveralls-lcov command sends the content of the source file always.
Could you ask it to coveralls.io?

**Comment by Nic30** [comment]
> coveralls-lcov command sends the content of the source file always.

I should have look at report first. That is true.

> Could you ask it to coveralls.io?

OK I will check if output is entirely correct and then ask coveralls.

**Comment by Nic30** [comment]
Actually coveralls never responded.
