### ISSUE TITLE
GitHub Actions support

### ISSUE THREAD

**Issue by sjaeckel** [okkez/coveralls-lcov#25]
Hi,

first let me thank you for such an easy way to have coveralls support for already a long time on travis :)

I'm trying to use this together with GitHub actions, is this already somehow supported?
I tried to find information on it, but couldn't find anything on how to do it.

If it's not supported yet, is there a chance to get support for GitHub actions as CI provider?

Thanks in advance & Cheers

**Comment by okkez** [comment]
Please try `--service-name`, `--service-job-id`, `--service-pull-request` option.

GitHub Actions provides some environment variables.

https://docs.github.com/en/actions/learn-github-actions/environment-variables

**Comment by sjaeckel** [comment]
Gotcha!

Thanks for the correct pointers :)

This invocation

```
coveralls-lcov coverage.info --service-job-id="$GITHUB_RUN_ID" --service-name="github" --repo-token="$REPO_TOKEN" --branch="$GITHUB_REF_NAME" --service-pull-request="$PR_NUMBER"
```

in combination with the following env in the Github action yml made it work!

```
        env:
          PR_NUMBER: ${{ github.event.number }}
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
