### ISSUE TITLE
coveralls-lcov fails on travis-ci

### ISSUE THREAD

**Issue by droundy** [okkez/coveralls-lcov#5]
Hello, I'm getting the following message when running coveralls-lcov on travis-ci:

```
$ coveralls-lcov coverage.info
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/coveralls-lcov-1.1.2/lib/coveralls/lcov/converter.rb:28:in `readlines': No such file or directory - coverage.info (Errno::ENOENT)
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/coveralls-lcov-1.1.2/lib/coveralls/lcov/converter.rb:28:in `parse_tracefile'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/coveralls-lcov-1.1.2/lib/coveralls/lcov/converter.rb:12:in `convert'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/coveralls-lcov-1.1.2/lib/coveralls/lcov/runner.rb:59:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/coveralls-lcov-1.1.2/bin/coveralls-lcov:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/coveralls-lcov:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/coveralls-lcov:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'

```

I'm not sure what the problem is and have never used ruby, but it sounds like the File.readlines isn't working for some reason.  For more details, you can look at my travis output:

https://travis-ci.org/droundy/bigbro/jobs/136295177

**Comment by okkez** [comment]
Log says:

> No such file or directory - coverage.info (Errno::ENOENT)

coverage.info does not exist in current directory.

You can debug using `pwd` and `ls` command in .travis.yml.

**Comment by droundy** [comment]
Thanks, I did not see that (and feel silly now that I do see it)!  I wonder if it would be possible to give a clearer error message in this case? (In particular, without the stack trace!) It's easy to miss the actual error message in the middle of the lengthy stack trace, and I expect this kind of typo (in this case do to renaming the file and forgetting to change it in this line of my travis config) is pretty common.

**Comment by okkez** [comment]
Thank you for reporting issue. I will fix error message.

**Comment by okkez** [comment]
New version released.
